[theme]
# FusionViewer settings (I'm not sure yet why this causes a problem)
base="light"
#primaryColor="purple"

# original settings
#base="dark"
backgroundColor="#1e1e1e"
secondaryBackgroundColor="#252526"
